image:
  - Ubuntu
  - Visual Studio 2017

platform:
  - x64
  - x86

environment:
  RACKET_VERSION: 7.2
  CYGPATH: cygpath -u # used by download-racket.sh on Windows

# only build commits where the message starts with "BUILD"
only_commits:
  message: /^BUILD/

############################################################################
# os- and platform-specific configuration

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x64

    environment:
      PKG_DIR: libgit2-win32-x86_64

    before_build: &windows_before_build
      - git clone https://github.com/liberalartist/appveyor-racket.git C:\a-r
      - bash C:\a-r\download-racket.sh C:\install-racket.exe
      - C:\install-racket.exe /S /D=C:\racket
      - set PATH=%PATH%;C:\racket\

    build_script: &windows_build_script
      - racket make-libgit2.rkt

    before_test: &windows_before_test
      - raco pkg install -i --link %PKG_DIR%

    test_script: &windows_test_script
      - racket test-script.rkt

  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x86

    environment:
      PKG_DIR: libgit2-win32-i386

    before_build: *windows_before_build

    build_script: *windows_build_script

    before_test: *windows_before_test

    test_script: *windows_test_script
      
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x64

    environment:
      PKG_DIR: libgit2-x86_64-linux
        
    before_build: &linux_before_build
      - git clone --branch i386 https://github.com/liberalartist/travis-racket.git ~/travis-racket
      - export RACKET_DIR="~/racket"
      - cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
      - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

    build_script: &linux_build_script
      - ~/racket/bin/racket make-libgit2.rkt

    before_test: &linux_before_test
      - ~/racket/bin/raco pkg install -i --link "$PKG_DIR"

    test_script: &linux_test_script
      - ~/racket/bin/racket test-script.rkt
      
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x86

    environment:
      PKG_DIR: libgit2-i386-linux
        
    before_build: *linux_before_build

    build_script: *linux_build_script

    before_test: *linux_before_test

    test_script: *linux_test_script
      
############################################################################
# get the src submodule
install:
  - git submodule init
  - git submodule update

# save the build package
artifacts:
  - path: $(PKG_DIR)

