image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

environment:
  RACKET_VERSION: 7.2
  CYGPATH: cygpath -u # used by download-racket.sh on Windows

# only build commits where the message starts with "BUILD"
only_commits:
  message: /^BUILD/

# get the src submodule
install:
  - git submodule init
  - git submodule update

# save the build package
artifacts:
  - path: $(PKG_DIR)

############################################################################
# os- and platform-specific configuration

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    environment:
      PKG_DIR: libgit2-win32-x86_64
      RKT_GIT_NO_CTEST: NO_CTEST # for fast debugging only

    before_build: &windows_before_build
      - git clone https://github.com/liberalartist/appveyor-racket.git C:\a-r
      - bash C:\a-r\download-racket.sh C:\install-racket.exe
      - C:\install-racket.exe /S /D=C:\racket
      - set PATH=%PATH%;C:\racket\

    build_script: &common_build_script
      - racket make-libgit2.rkt

    before_test: &windows_before_test
      - ps: get-command "C:\projects\native-libgit2-pkgs\build\win32\x86_64\Debug\git2.dll" | format-list
      - cmd: python .\py-w64-test-tmp.py
      - raco test tmp-w64-test.rkt
      - raco pkg install -i --link %PKG_DIR%

    test_script: &common_test_script
      - raco test test-script.rkt
      
  -
    matrix:
      only:
        - image: Ubuntu

    environment:
      PKG_DIR: libgit2-x86_64-linux
        
    before_build: &linux_before_build
      - git clone --branch i386 https://github.com/liberalartist/travis-racket.git ~/travis-racket
      - export RACKET_DIR=~/racket
      - cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
      - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

    build_script: *common_build_script

    before_test: &linux_before_test
      - raco pkg install -i --link "$PKG_DIR"

    test_script: *common_test_script



