image:
  - Visual Studio 2017

platform:
  - x86
  - x64

install:
  - git submodule init
  - git submodule update

build_script:
  - mkdir w
  - cd w
  - cmake ../src
  - cmake --build .

test_script:
  - ctest -V

artifacts:
  - path: w
    name: build directory

